<?php

namespace App\Application\Cursos\DTOs;

final readonly class CursoDTO
{
    public function __construct(
        public int     $id_programa,
        public ?string $nombre_programa,
        public ?string $slug,
        public ?string $descripcion,
        public ?string $objetivo,
        public ?string $dirigido,
        public ?string $requisitos,
        public ?string $inversion,
        public ?float  $costo_monto,
        public ?string $creditaje,
        public ?string $nota,
        public ?string $foto,
        public ?string $imagen_banner_url,
        public ?string $imagen_alt,
        public ?string $url_video,
        public ?string $url_whatsapp,
        public ?string $url_whatsapp2,
        public ?string $titulo_documento1,
        public ?string $documento1,
        public array   $imagenes,
        public ?string $inicio_actividades,
        public ?string $finalizacion_actividades,
        public ?string $inicio_inscripciones,
        public ?string $mes_facturacion,
        public ?string $tipo_honorario,
        public ?int    $id_tipoprograma,
        public ?int    $categoria_web_id,
        public ?int    $formulario_id,
        public ?int    $area_id,
        public ?int    $id_plan,
        public ?int    $id_plandoc,
        public ?int    $id_imp,
        public ?int    $convenio_id,
        public ?int    $vendedor_id,
        public ?string $vendedor_nombre,
        public int     $estado,
        public ?string $estado_web,
        public bool    $destacado,
        public int     $orden,
        public ?string $meta_titulo,
        public ?string $meta_descripcion,
        public ?string $mensaje_exito,
        public ?string $fecha_publicacion,
        public ?string $fecha_reg,
        public ?string $updated_at,
        public ?string $plan_titulo,
        public ?float  $plan_costo,
        public ?int    $plan_nro_cuotas,
        public ?float  $plan_costo_por_cuota,
        public array   $cuotas,
        public ?int    $total_inscritos = null,
        public ?float  $total_recaudado = null,
    ) {}

    public function withCuotas(array $cuotas): self
    {
        return new self(
            id_programa:              $this->id_programa,
            nombre_programa:          $this->nombre_programa,
            slug:                     $this->slug,
            descripcion:              $this->descripcion,
            objetivo:                 $this->objetivo,
            dirigido:                 $this->dirigido,
            requisitos:               $this->requisitos,
            inversion:                $this->inversion,
            costo_monto:              $this->costo_monto,
            creditaje:                $this->creditaje,
            nota:                     $this->nota,
            foto:                     $this->foto,
            imagen_banner_url:        $this->imagen_banner_url,
            imagen_alt:               $this->imagen_alt,
            url_video:                $this->url_video,
            url_whatsapp:             $this->url_whatsapp,
            url_whatsapp2:            $this->url_whatsapp2,
            titulo_documento1:        $this->titulo_documento1,
            documento1:               $this->documento1,
            imagenes:                 $this->imagenes,
            inicio_actividades:       $this->inicio_actividades,
            finalizacion_actividades: $this->finalizacion_actividades,
            inicio_inscripciones:     $this->inicio_inscripciones,
            mes_facturacion:          $this->mes_facturacion,
            tipo_honorario:           $this->tipo_honorario,
            id_tipoprograma:          $this->id_tipoprograma,
            categoria_web_id:         $this->categoria_web_id,
            formulario_id:              $this->formulario_id,
            area_id:                  $this->area_id,
            id_plan:                  $this->id_plan,
            id_plandoc:               $this->id_plandoc,
            id_imp:                   $this->id_imp,
            convenio_id:              $this->convenio_id,
            vendedor_id:              $this->vendedor_id,
            vendedor_nombre:          $this->vendedor_nombre,
            estado:                   $this->estado,
            estado_web:               $this->estado_web,
            destacado:                $this->destacado,
            orden:                    $this->orden,
            meta_titulo:              $this->meta_titulo,
            meta_descripcion:         $this->meta_descripcion,
            mensaje_exito:            $this->mensaje_exito,
            fecha_publicacion:        $this->fecha_publicacion,
            fecha_reg:                $this->fecha_reg,
            updated_at:               $this->updated_at,
            plan_titulo:              $this->plan_titulo,
            plan_costo:               $this->plan_costo,
            plan_nro_cuotas:          $this->plan_nro_cuotas,
            plan_costo_por_cuota:     $this->plan_costo_por_cuota,
            cuotas:                   $cuotas,
            total_inscritos:          $this->total_inscritos,
            total_recaudado:          $this->total_recaudado,
        );
    }

    public static function fromModel(object $m): self
    {
        return new self(
            id_programa:              (int) $m->id_programa,
            nombre_programa:          $m->nombre_programa ?? null,
            slug:                     $m->slug ?? null,
            descripcion:              $m->descripcion ?? null,
            objetivo:                 $m->objetivo ?? null,
            dirigido:                 $m->dirigido ?? null,
            requisitos:               $m->requisitos ?? null,
            inversion:                $m->inversion ?? null,
            costo_monto:              isset($m->costo_monto) && $m->costo_monto !== null ? (float) $m->costo_monto : null,
            creditaje:                $m->creditaje ?? null,
            nota:                     $m->nota ?? null,
            foto:                     $m->foto ?? null,
            imagen_banner_url:        $m->imagen_banner_url ?? null,
            imagen_alt:               $m->imagen_alt ?? null,
            url_video:                $m->url_video ?? null,
            url_whatsapp:             $m->url_whatsapp ?? null,
            url_whatsapp2:            $m->url_whatsapp2 ?? null,
            titulo_documento1:        $m->titulo_documento1 ?? null,
            documento1:               $m->documento1 ?? null,
            imagenes:                 self::normalizarImagenes($m->imagenes ?? null),
            inicio_actividades:       $m->inicio_actividades ? (string) $m->inicio_actividades : null,
            finalizacion_actividades: $m->finalizacion_actividades ? (string) $m->finalizacion_actividades : null,
            inicio_inscripciones:     $m->inicio_inscripciones ? (string) $m->inicio_inscripciones : null,
            mes_facturacion:          $m->mes_facturacion ?? null,
            tipo_honorario:           $m->tipo_honorario ?? null,
            id_tipoprograma:          $m->id_tipoprograma ? (int) $m->id_tipoprograma : null,
            categoria_web_id:         $m->categoria_web_id ? (int) $m->categoria_web_id : null,
            formulario_id:              $m->formulario_id ? (int) $m->formulario_id : null,
            area_id:                  $m->area_id ? (int) $m->area_id : null,
            id_plan:                  $m->id_plan ? (int) $m->id_plan : null,
            id_plandoc:               $m->id_plandoc ? (int) $m->id_plandoc : null,
            id_imp:                   $m->id_imp ? (int) $m->id_imp : null,
            convenio_id:              $m->convenio_id ? (int) $m->convenio_id : null,
            vendedor_id:              ($m->vendedor_id ?? null) ? (int) $m->vendedor_id : null,
            vendedor_nombre:          ($m->vendedor_nombre ?? null) ?: null,
            estado:                   (int) ($m->estado ?? 1),
            estado_web:               $m->estado_web ?? 'borrador',
            destacado:                (bool) ($m->destacado ?? false),
            orden:                    (int) ($m->orden ?? 0),
            meta_titulo:              $m->meta_titulo ?? null,
            meta_descripcion:         $m->meta_descripcion ?? null,
            mensaje_exito:            $m->mensaje_exito ?? null,
            fecha_publicacion:        $m->fecha_publicacion ? (string) $m->fecha_publicacion : null,
            fecha_reg:                $m->fecha_reg ? (string) $m->fecha_reg : null,
            updated_at:               ($m->updated_at ?? null) ? (string) $m->updated_at : null,
            plan_titulo:              $m->plan_titulo ?? ($m->plan_titulo_alt ?? null),
            plan_costo:               isset($m->plan_costo) && $m->plan_costo !== null ? (float) $m->plan_costo : null,
            plan_nro_cuotas:          isset($m->plan_nro_cuotas) && $m->plan_nro_cuotas !== null ? (int) $m->plan_nro_cuotas : null,
            plan_costo_por_cuota:     isset($m->plan_costo_cuota) && $m->plan_costo_cuota !== null ? (float) $m->plan_costo_cuota : null,
            cuotas:                   [],
            total_inscritos:          isset($m->total_inscritos) ? (int) $m->total_inscritos : null,
            total_recaudado:          isset($m->total_recaudado) ? (float) $m->total_recaudado : null,
        );
    }

    private static function normalizarImagenes(mixed $valor): array
    {
        if (is_array($valor)) {
            return $valor;
        }
        if (is_string($valor)) {
            $decoded = json_decode($valor, true);
            return is_array($decoded) ? $decoded : [];
        }
        return [];
    }
}
